#+TITLE: My Death Along With Fuhrer
#+AUTHOR: ArionRefat
#+DESCRIPTION: A dream that I dreamt about

* What is this?
I saw dreams every night that are very unpleasant or maybe even shocking. Dreams are very mysteries in nature. It does remind me of how complex our mind is. Anyway Let's get to it, These are going to be just interprets of my dreams and some opinions on my own about it.

* Story:
** Chapter 1:
It was my 50th Birthday. I was celebrating my birthday with friends and family. Night fall and they all left and I'm alone again thinking about my accomplishments over the years. What I have done in last 30 years. I got job at FAANG, dream job of everyone specially how competitive it is. I got enough money by now. Enough money to buy and enjoy anything. I got a farm. I got animals to take care of and they take care of me. I have virtually got everything that I ever wanted in my life but still I was empty inside, I feel like I have got nothing yet everything. I got everything I ever wanted, I wanted be a musician, a DJ, a car ricer, chef, Internet personality, businessman, street food seller etc, etc. Everything one could ever dreamed of. Maybe there is nothing left other than getting old. I don't want to get old. Being old is not a good experience. I have seen my parents, I have seen their parents, what happens to them after they age. I can assured myself that no I don't want to old. I don't want to end up like old folks who doesn't have the ability to defend themselves rather rely on other's mercy.
** Chapter 2:
What I decided in that dream was to kill myself as soon as possible. Not just some kind of suicide but a glorious death like fuhrer's. I wanted to make my death special, as it will be an another accomplishment of my life. I wanted to make a mark on this world, just like the fuhrer did. I saw I did something that I will explain in another article. After that I got enough attention. I started to prepare for my death, I went to Deutschland. I choose a place beside a forest and started digging the grave and set the cameras and other equipments beside that. I start the live stream and started to explain my cause. After that I switch my cameras which was placed above my grave. I slowly lie down towards the grave and execute my script.
** Final Chapter:
I wrote a script that will execute some process, First it will start the live stream at least 10 minutes later so that people don't get in my way then switches the cameras automatically as I approach the grave. I lie down and cocks the gun and shoot myself right through my heart. As bloods spouts out from the bullet hole I experience the death, I was feeling the pain and right around this time the memories started to appear right in front of my eyes. I started to see myself and my accomplishments but I realize all these accomplishments in my life, all these knowledge will be nothing in the next few moments. But it was too late to think anything, as the final stage had already started gallons of petrol started to pour like a waterfall and finally, the fire had been sparked. Time to burn my existence. As the fire started to burn my flesh, I started screaming, but screaming out of joy or pain? I honestly don't know. And that's where it ended.
